### ISSUE TITLE
Four tests of openfasttrace-0.5.0 on Win10 failed 

### ISSUE THREAD

**Issue by quarterbit** [itsallcode/openfasttrace#119]
Just downlaoded the release and ran mvn test -e. 
Got some error related to character encoding. 

[..] Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match. [..] 
Stack trace attached. 

[test-tom_win10.txt](https://github.com/itsallcode/openfasttrace/files/1799781/test-tom_win10.txt)

**Comment by redcatbear** [comment]
@kaklakariada: since I don't have a Windows machine, could you please give this one a closer look?

**Comment by kaklakariada** [comment]
I will look into this.

**Comment by redcatbear** [comment]
@quarterbit: Were your tests successful?

**Comment by quarterbit** [comment]
Still have two failed tests. 
[console.txt](https://github.com/itsallcode/openfasttrace/files/1996479/console.txt)
[surefire-reports.zip](https://github.com/itsallcode/openfasttrace/files/1996480/surefire-reports.zip)

**Comment by quarterbit** [comment]
I would fix it in the code but I may need a short help intro to setup the dev environment..

**Comment by kaklakariada** [comment]
@quarterbit Which branch did you use? This is not yet merged into `develop`. Please use branch `fix_path_matcher_tests_windows`.

**Comment by kaklakariada** [comment]
@quarterbit #131 is now merged into `develop`. Please try again.

**Comment by quarterbit** [comment]
Works now. 
[WARNING] Tests run: 302, Failures: 0, Errors: 0, Skipped: 3
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.1:report (report) @ openfasttrace ---
[INFO] Loading execution data file C:\Users\Tom\git\openfasttrace\target\jacoco.exec
[INFO] Analyzed bundle 'OpenFastTrace' with 91 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ---------------
