### ISSUE TITLE
Reanable SONAR

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/openfasttrace#134]
# Description
SONAR is currently switched of since it deletes review comments of the user account it is running under in the branch it checks.

The SONAR people acknowledged this behavior and said they are going to fix it. We deactivated SONAR for the time being and will re-enable it once the bug is fixed.

## Steps to Reproduce
1. Configure SONAR on a branch
2. Write a review on the branch
3. Run a build that includes SONAR running under the same user who did the review
4. Make modifications
5. Run the build again
6. SONAR deletes old comments (including the ones it did not produce itself) before adding findings.

## Expected behavior
SONAR only deletes comments that it created.

# Environment
GitHub, SONAR

**Comment by redcatbear** [comment]
@kaklakariada is the Sonar fix available meanwhile?

**Comment by kaklakariada** [comment]
Not according to the [documentation](https://docs.travis-ci.com/user/sonarcloud/#Analysis-of-internal-pull-requests). The need for a separate github account will be [removed](https://docs.travis-ci.com/user/sonarcloud/#Upcoming-improvements).

**Comment by redcatbear** [comment]
Fixed.
