### ISSUE TITLE
Import files from a ZIP file

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/openfasttrace#136]
**Is your feature request related to a problem? Please describe.**
Big projects reference top level requirements from a maven repository. These requirements are stored as specobject xml files inside a ZIP file.

**Describe the solution you'd like**
A new import shall read the content of a ZIP file and delegate to other importers depending on the file name.

**Describe alternatives you've considered**
Unpacking the ZIP would require additional work outside of OFT and requires slow disk operations.

**Additional context**
(none)

**Comment by redcatbear** [comment]
Closed with #137.
