### ISSUE TITLE
Tags filter removes too many items

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/openfasttrace#145]
# Description
The tag filter also removes/hides items that cover the requirements

## Steps to Reproduce
1. Create spec item s1 with tag `foo` and required type `dsn`
2. Create spec item s2 without tag that covers s1
3. Run tracing with tag filter `foo`

## Expected behavior
Report includes s1 and s2, shows that s1 is covered by s2

## Actual behavior
Report only contains s1 with missing coverage

**Comment by redcatbear** [comment]
As we discussed, we will fix this by adding a switch that lets you choose whether the tag filter accept only items that have one of the tags or also items that have no tags.

**Comment by redcatbear** [comment]
It's not really a bug in the tag filter, but definitely needs improvement for the scenario that you described.
