### ISSUE TITLE
Failed to apply plugin [id 'org.itsallcode.openfasttrace'] -  Could not generate a proxy class for class 

### ISSUE THREAD

**Issue by sascha15432** [itsallcode/openfasttrace#152]
# Description
When calling ./gradlew.bat --stacktrace --debug --no-daemon info traceRequirements  OFT fails with  "Could not generate a proxy class for class ..." 

## Steps to Reproduce
1.  ./gradlew.bat --stacktrace --debug --no-daemon info traceRequirements 

## Expected behavior
./gradlew.bat --stacktrace --debug --no-daemon info traceRequirements shall start without  "[org.gradle.internal.buildevents.BuildExceptionReporter]"

# Environment
- OFT: [ 0.1.0]
- OS: [Windows 10]
- Java Version: ["1.8.0_162"]
- Maven Version (in case of build problems only): [3.5.3]

## Additional context
11:30:00.142 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.ClassNotFoundException: org.gradle.api.file.RegularFileProperty

**Comment by sascha15432** [comment]
A Windows path / file system issue?

**Comment by sascha15432** [comment]
build.gradle: 


buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.org.itsallcode:openfasttrack-gradle:0.1.0"
  }
}


plugins {
  id "org.itsallcode.openfasttrace" version "0.1.0"
}

apply plugin: "org.itsallcode.openfasttrace"


task info {
	description "prints project info"
	group "build"
} << {
	info "* ***************************"
	info "* version: ${version}"
	info "* group: ${group}"
	info "* date: ${date}"
	info "* root: ${rootProject}"
	info "* BuildNr: ${buildNumber}"
	info "* BuildURL: ${buildURL}"
	info "* ***************************"
}

**Comment by sascha15432** [comment]
JENKINSFILE

 stage('Trace requirements') {
        
       if(isUnix()){

                 sh "./gradlew $gradleOptions info traceRequirements"

            } else{
       
                    bat "./gradlew.bat $gradleOptions info traceRequirements"
            }
      }

**Comment by redcatbear** [comment]
Can you move issue tickets that relate to the Gradle-Plugin to https://github.com/itsallcode/openfasttrace-gradle/issues please?

@kaklakariada: Can you please copy the issue templates there?

**Comment by kaklakariada** [comment]
Closing this ticket, moved to https://github.com/itsallcode/openfasttrace-gradle/issues/7
