### ISSUE TITLE
Don't mark source tag as "not ok" when covered requirement is not ok

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/openfasttrace#166]
**Is your feature request related to a problem? Please describe.**
* Requirement A needs coverage from `src` and `test`
* There is only a tag for covering tag `src`, so the requirement is marked as "not ok" in the report :heavy_check_mark: 
* The tag covering `src` is marked as "not ok" in the report :x: This is confusing.

**Describe the solution you'd like**
* Show the tag covering `src` as OK even when covering requirement is not ok
* Or add a mark saying "Tag is OK but the covered requirement is not ok"

**Comment by redcatbear** [comment]
I think we should differentiate in the report between covered shallow (search for the problem deeper down the chain) and uncovered (the problem is right here in front of your eyes).
