### ISSUE TITLE
Migrate to Java 11

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/openfasttrace#187]
As a developer
I want OFT to be built with Java
in order to avoid problems caused by the end of public updates for Java 8 in January 2019.

## Context
See https://www.oracle.com/technetwork/java/eol-135779.html for information about the EOL plans for the Oracle JDK.

Realistically with JDK 11 support for the Oracle JDK will not be guaranteed anymore by the OFT project due to Oracle's announcements to not provide it for free anymore. We recommend our users run OFT on the OpenJDK instead.

**Comment by kaklakariada** [comment]
Migration to Java 11 already done.
