### ISSUE TITLE
Support tracing for more languages

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/openfasttrace#233]
Currently only `.java` files are supported for tracing. We need to support more languages and make the file suffix configurable.

@stemas implemented support for `.ts`: https://github.com/itsallcode/openfasttrace/compare/develop...stemas:feature/asciidoc

**Comment by redcatbear** [comment]
See also #353.

**Comment by redcatbear** [comment]
Will fix #352 when implemented.

**Comment by redcatbear** [comment]
The list of supported extensions is quite extensive and recently no one asked for extensions not on the list. Closing this ticket until concrete request comes in.
