### ISSUE TITLE
Add maven plugin phase that creates design template

### ISSUE THREAD

**Issue by jakobbraun** [itsallcode/openfasttrace#252]
It would be very helpful to have a command like `mvn openfasttrace:generate-design` that creates a skeleton document for a design with one design element for each requirement.

A more general solution would be a `fix` foal that creates the sceletons wherever possible and guides the using a todolist output through the manual steps.

**Comment by redcatbear** [comment]
This is a little bit much effort at the moment compared to simply copying the files. Closing ticket.
