### ISSUE TITLE
Add flag for not implemented designs

### ISSUE THREAD

**Issue by jakobbraun** [itsallcode/openfasttrace#253]
I would like to mark some design or requirement elements as "not yet implemented".

My suggestion is to check for elements containing this string. OFT then should not fail if it can't find the required references in the code.

By that, I can already add the complete design and let it pass the CI, while some features are still pending.

Optionally OFT could print a warning for those design elements.

By convention, one could also add a ticket number of the ticket that contains the feature.

**Comment by redcatbear** [comment]
This feature is implemented in the ASPEC reporter only so far. In the Markdown world we assume that only requirements are in the spec that are approved. The Linked spec objects are prepared for the feature, but this is not a priority at the moment. Closing this ticket.
