### ISSUE TITLE
HTML report is green while console report shows defects

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [itsallcode/openfasttrace#303]
# Description

When I run this command `java -jar "$tmp_file" trace -o html > report.html`, the report is green:
![Screenshot from 2021-11-12 10-57-43](https://user-images.githubusercontent.com/46891819/141449024-0844fe8a-628c-49e9-8dcb-4605ebdfaf5a.png)

When I run this command `java -jar "$tmp_file" trace`, the report contains defects:

`not ok - 170 total, 6 defect`

And the second report is right because I have some typos and missing tracking comments in the code.

## Steps to Reproduce

Can be reproduced on the following commit with the commands described above: https://github.com/exasol/exasol-rest-api/commit/ff918b484d1f73ad40ef16ca38d1081f28983f0d

## Expected behavior

I expect to see the same report in HTML format and on the console

# Environment

- OFT: 3.3.0
- OS: Ubuntu 20.04.2 LTS
- Java Version: openjdk 11.0.11 2021-04-20

**Comment by redcatbear** [comment]
@kaklakariada , please check if this is still reproducible.

**Comment by kaklakariada** [comment]
Problem still exists with the latest OFT version from `main`.

<details>
<summary>Output of failed `oft trace` run</summary>

```
% oft trace
not ok [ in:  2 /  2 ✔ | out:  1 /  1 ✔ ] dsn~get-tables-headers~1 (impl, -itest)

  The endpoint requires `Authorization` header with an API token to handle requests.

  [covered shallow  ] ← impl~get-tables-headers-2891709974~0
  [covered shallow  ] ← impl~get-tables-headers-3531088591~0
  [covers           ] → req~get-tables~1

not ok [ in:  3 /  3 ✔ | out:  1 /  1 ✔ ] dsn~get-tables-response-body~1 (impl, utest, -itest)

  The endpoint has the following JSON response body format:
  
  ```json
  {
    "status": <"ok" | "error">,
    "tablesList": [
      {
        "schemaName": "<schema>",
        "tableName": "<table>"
      },
      ...
    ],
    // in case of "error"
    "exception": "<error code and message>"
  }
  ```

  [covered shallow  ] ← impl~get-tables-response-body-1355644338~0
  [covered shallow  ] ← impl~get-tables-response-body-1969744724~0
  [covers           ] → req~support-json-request-and-response-format~1
  [covered shallow  ] ← utest~get-tables-response-body-1974856277~0

not ok [ in:  0 /  0   | out:  1 /  1 ✔ ] dsn~insert-row-endpoint~1 (-impl, -itest)

  ERA provides the following endpoint to the API users: `/api/v1/row [post]`

  [covers           ] → req~insert-row~1

not ok [ in:  3 /  3 ✔ | out:  1 /  1 ✔ ] dsn~update-rows-endpoint~1 (itest, -impl)

  ERA provides the following endpoint to the API users: `/api/v1/rows [put]`

  [covered shallow  ] ← itest~update-rows-endpoint-1213195701~0
  [covered shallow  ] ← itest~update-rows-endpoint-1753944288~0
  [covered shallow  ] ← itest~update-rows-endpoint-3147567381~0
  [covers           ] → req~update-rows~1

not ok [ in:  1 /  1 ✔ | out:  1 /  1 ✔ ] dsn~update-rows-response-body~1 (impl, -itest)

  The endpoint has the following JSON response body format:
  
  ```json
  {
    "status": <"ok" | "error">,
    // in case of "error"
    "exception": "<error code and message>"
  }
  ```

  [covered shallow  ] ← impl~update-rows-response-body-1134536244~0
  [covers           ] → req~support-json-request-and-response-format~1

not ok [ in:  9 /  9 ✔ | out:  0 /  0   ] feat~exasol-rest-endpoints~1 (req)

  ERA provides REST API endpoints that allow API Users to interact with the Exasol database.

  [covered shallow  ] ← req~communication-with-exasol~1
  [covered shallow  ] ← req~delete-rows~1
  [covered shallow  ] ← req~execute-query~1
  [covered shallow  ] ← req~execute-statement~1
  [covered shallow  ] ← req~get-rows~1
  [covered shallow  ] ← req~get-tables~1
  [covered shallow  ] ← req~insert-row~1
  [covered shallow  ] ← req~support-json-request-and-response-format~1
  [covered shallow  ] ← req~update-rows~1

not ok [ in:  2 /  2 ✔ | out:  1 /  1 ✔ ] req~get-tables~1 (dsn)

  API users can get a list of table names by a schema name.

  [covered shallow  ] ← dsn~get-tables-endpoint~1
  [covered shallow  ] ← dsn~get-tables-headers~1
  [covers           ] → feat~exasol-rest-endpoints~1

not ok [ in:  2 /  2 ✔ | out:  1 /  1 ✔ ] req~insert-row~1 (dsn)

  API users can insert a single row into a table.

  [covered shallow  ] ← dsn~insert-row-endpoint~1
  [covered shallow  ] ← dsn~insert-row-headers~1
  [covers           ] → feat~exasol-rest-endpoints~1

not ok [ in: 11 / 11 ✔ | out:  1 /  1 ✔ ] req~support-json-request-and-response-format~1 (dsn)

  ERA supports a JSON request and response format.

  [covered shallow  ] ← dsn~delete-rows-request-body~1
  [covered shallow  ] ← dsn~delete-rows-response-body~1
  [covered shallow  ] ← dsn~execute-query-response-body~1
  [covered shallow  ] ← dsn~execute-statement-request-body~1
  [covered shallow  ] ← dsn~execute-statement-response-body~1
  [covered shallow  ] ← dsn~get-rows-response-body~1
  [covered shallow  ] ← dsn~get-tables-response-body~1
  [covered shallow  ] ← dsn~insert-row-request-body~1
  [covered shallow  ] ← dsn~insert-row-response-body~1
  [covered shallow  ] ← dsn~update-rows-request-body~1
  [covered shallow  ] ← dsn~update-rows-response-body~1
  [covers           ] → feat~exasol-rest-endpoints~1

not ok [ in:  2 /  2 ✔ | out:  1 /  1 ✔ ] req~update-rows~1 (dsn)

  API users can update rows from a table based on a condition.

  [covered shallow  ] ← dsn~update-rows-endpoint~1
  [covered shallow  ] ← dsn~update-rows-headers~1
  [covers           ] → feat~exasol-rest-endpoints~1


not ok - 162 total, 10 defect
```

</details>

Output of `oft trace -o html > /tmp/report.html`: [report.html](https://github.com/itsallcode/openfasttrace/files/10343965/report.txt)
