### ISSUE TITLE
Failing on really basic OFT use cases

### ISSUE THREAD

**Issue by less0** [itsallcode/openfasttrace#325]
I started to use OFT for a project and I really like the approach, but I'm certainly missing some information required to make use of it productively. I've read the User Guide (more than once), tried to skin through the source for examples, tried to search Google, but to no avail. I'm really eager to enhance the guide to make the onboarding easier for newbies, but in order to be able to I need to know how these work:

- I do not know how to cover a spec item from another one, both in (different) Markdown files
  - In my case I have a `feat` and would like to cover it with a `req` 
- I do not know how  to name a spec item in a source file
  - With the tag syntax, I have been able to cover a spec item, but the `impl` spec item gets a name derived from the `req` spec item, which is not what I want. Is there a way to name the `impl` item and even give it a title maybe?

These are the most basic use cases I'm unsuccessfully trying to cover at the moment and more might arise when going further, but I'd be really grateful if someone could give me some hints on it.

**Comment by redcatbear** [comment]
@less0 , thank you very much for that valuable feedback. This tells me that we still have a lot of work to do on the user guide.

Where do you have your main trouble? Is it with the syntax of the requirements or with usage of the OFT application?

**Comment by less0** [comment]
@redcatbear Thank you very much. I'm currently analyzing the `MarkdownImporter.java` and it helps a lot to understand how to write spec items (at least in Markdown). Especially I did not know about all the keywords available in spec items and it makes **much** more sense now. From the user guide it's not becoming clear, that `Rationale` and `Comment` are keywords, for instance.

I might make a proposal for an enhanced `user_guide.md` in the next few days.

**Comment by kaklakariada** [comment]
Closing this as #328 is merged now.
