### ISSUE TITLE
C# Files are not recognized properly

### ISSUE THREAD

**Issue by less0** [itsallcode/openfasttrace#326]
# Description
OFT expects C# to have the file extension `.c#`, but the default extension in the .NET World is `.cs`, therefor C# that is in a `.cs` file is ignored by OFT.  

## Steps to Reproduce
1. Extract the files from [Demo.zip](https://github.com/itsallcode/openfasttrace/files/9235305/Demo.zip)
2. Run OFT on the folder the files were extracted to

## Expected behavior
The spec object `req~demo~1` should be covered, because it's tagged in the `Test.cs` file, but is not. If the file is renamed to `Test.c#` it's covered correctly.

# Environment
- OFT: 3.5.0
- OS: macOS 10.14.6
- Java Version: 18.0.2+9-61

**Comment by redcatbear** [comment]
Added support for `.cs` extension in `TagImporterFactory`. @kaklakariada, please review #326.

**Comment by redcatbear** [comment]
@less0, I fixed the '.cs' issue. The change is now on the `develop` branch and will be part of the next release. Sorry that it took so long, but at the moment I only have time on the weekend.

**Comment by kaklakariada** [comment]
@less0, this is fixed in release [3.6.0](https://github.com/itsallcode/openfasttrace/releases/tag/3.6.0).
