### ISSUE TITLE
OFT fails on input files with non UTF-8 encoding 

### ISSUE THREAD

**Issue by ckunki** [itsallcode/openfasttrace#363]
# Description
OFT fails on input files with non UTF-8 encoding with error message 
```
Execution default-cli of goal org.itsallcode:openfasttrace-maven-plugin:1.6.1:trace failed: 
Error reading <path> at line 0: Input length = 1 
```

## Steps to Reproduce
1. Create input file OFT with non UTF-8 char sequence, e.g. German umlaut or forward-tick (accent acute, char code 0xB4)
2. run OFT 

## Expected behavior
Error message, e.g. file xyz contains invalid UTF-8 sequence "xxx" in line <line-number> .

# Environment
- OFT: 1.6.1
- OS: Windows 10
- Java Version: jdk-11.0.15+10
- Maven Version:  3.8.6 

## Additional Information 
I used an editor which does not enforce UTF-8.

**Comment by kaklakariada** [comment]
This has the same error message as https://github.com/itsallcode/openfasttrace/issues/391 which is fixed by #392 .
