### ISSUE TITLE
A space behind a `Needs: ` specification item validates the requirement

### ISSUE THREAD

**Issue by qwc** [itsallcode/openfasttrace#364]
# Description
If you put a space behind any item of a `Needs: ` specification, it validates the requirement.
Which means, that the requirement is not considered a defect anymore, despite the fact that none of the needed further specifications have been made, e.g. dsn, req, ... 

These lead to a validated requirement:
- `Needs: req , dsn `
- `Needs: req `
- `Needs: req, dsn `
- `Needs: req ,dsn`
- `Needs: req,dsn `

Only two ways to not run into this bug:
- `Needs: req,dsn`
- `Needs: req, dsn`

## Steps to Reproduce
1. Write a requirement, it doesn't matter which, I tried a `feat`
2. Add the `Needs: ....` line with the variants i mentioned.

## Expected behavior
I expect that the parser correctly parses a comma separated list and trims the spaces from all items and actually even if an unknown element is in the list, doesnt just set the requirement to 'done'.

# Environment
- OFT: 3.7.0
- OS: Arch Linux 6.4.12-arch1-1
- Java Version: openjdk 11.0.20.1 2023-08-24

## Additional context
It's easy to fall into this trap through a simple typo, which could be avoided through proper parsing.
Especially when you have a lot of requirements to track, you will never witness the simple typo of a space behind one of the `Needs:` items...

**Comment by sebastianohl** [comment]
+1

OFT: 3.7.0
OS: Ubuntu 22.04
Java Version: openjdk version "19.0.2" 2023-01-17
