### ISSUE TITLE
The traceability report gets corrupted in a specific scenario

### ISSUE THREAD

**Issue by ayankuma** [itsallcode/openfasttrace#396]
# Description
When OFT is run using a specific file, the traceability report contains some unexpected characters (See "image" is unexpected in the attached screenshot).
![Screenshot 2024-02-29 at 10 12 52](https://github.com/itsallcode/openfasttrace/assets/91470115/cb2c12d6-2c62-4f5b-82a3-c1a3aacc0616)

## Steps to Reproduce
1. Use the below file. You can save it as test14_nr_spis.rst
 ```
Test case for assigning a specific number of SPIs to allocate for dom0less domain                       
=================================================================================                       

`XenValTestCase~arm64_assign_domain_SPIs~1`                                                             

Covers:
 - `XenSSR~arm64_assign_domain_SPIs~1`

Needs:                                                                                                  
 - XenValTestCode                                                                                       

Objectives                                                                                              
---------- 

The script is responsible for:
 - preparing kernel image (AArch64 linux image)                                                         

```
2. Run the below command
`java -jar /<path_to>/openfasttrace-3.7.1.jar trace -o html -f any.html  /<path_to>/test14_nr_spis.rst`

## Expected behavior
There should be no `image` in `Needs:`

# Environment
- OFT: [3.7.1]
- OS: [Ubuntu 20.04]
- Java Version: [openjdk 11.0.20.1 2023-08-24]

**Comment by ayankuma** [comment]
Reordering `Covers:` and `Needs:` makes this issue go away.

**Comment by kaklakariada** [comment]
I could reproduce the error and will fix it.
While investigating this, I found another bug that caused underlined headings not being recognized when the underlining `----` has trailing spaces.

**Comment by kaklakariada** [comment]
After talking with @redcatbear  the behavior of the Markdown importer is intended. The importer expects the description of an item after the ID and before Covers/Needs tags. Sections (either with `###` or underlined) should not be used within items.

So the solution of  reordering is correct.
