### ISSUE TITLE
Requirement item id name with dot and numbers

### ISSUE THREAD

**Issue by RobertZickler** [itsallcode/openfasttrace#417]
# Description
Following https://github.com/itsallcode/openfasttrace/blob/main/doc/user_guide.md#specification-item-id it states that

> The name part of the ID must be a character string consisting of Unicode letters and or numbers separated by underscore ("_"), hyphen ("-") or dot ("."). Whitespaces are not allowed.

We use IDs like "SR.AB.1.1.1" resulting in an item ID of `req~SR.AB.1.1.1~1`. But that gets ignored if I try to trace. If I replace all but the first dot the ID is traced again e.g. `req~SR.AB_1_1_1~1`. If I replace any other dot it will be ignored again e.g. the second dot `req~SR_AB.1_1_1~1`.

What does work is: If I have no number following a dot: `req~SR.AB.A1.B1.C1~1`. So that seems to be the issue here. No number directly after a dot.

# Environment
- OFT: 4.0.0
- OS: Windows 10
- Java Version: 22

**Comment by kaklakariada** [comment]
@RobertZickler Thanks for reporting this. We will fix this in the next release, see #418

**Comment by kaklakariada** [comment]
This is fixed in https://github.com/itsallcode/openfasttrace/releases/tag/4.0.1
