### ISSUE TITLE
Documentation bugs

### ISSUE THREAD

**Issue by RobertZickler** [itsallcode/openfasttrace#419]
In https://github.com/itsallcode/openfasttrace/blob/main/core/src/main/resources/usage.txt the command is `--report-verbosity`  in https://github.com/itsallcode/openfasttrace/blob/main/doc/user_guide.md#reference it is wrongly stated as `--verbosity-level`

If  `--verbosity-level` is used the error `oft: Unexpected parameter 'verbositylevel' is not allowed` is shown.
Also not sure if bug or feature: `-v` and `--v` both work. It is documented differently in the linked docs. Even `--------v all` and `------o html` (etc.) work. No sure if that breaks any standard?

Also if no argument is given the error message states: `oft: No value for argument 'reportverbosity'` With a missing dash.

For the latter that is also the case for `--wanted-tags`: `oft: No value for argument 'wantedtags'` And probably for more options (`outputformat`, ...)
Seems to happen here:  https://github.com/itsallcode/openfasttrace/blob/63c846a8736dbca98a0c8c2c28c8ae9fd4c0887a/core/src/main/java/org/itsallcode/openfasttrace/core/cli/CommandLineInterpreter.java#L131C22-L131C35

For `--output-format` the usage.txt states "plain", "html", "aspec" where as the user_guide.md does not state `aspec`

And the XML reporter has a mayor (and hard to find) typo in user_guide.md as well: In https://github.com/itsallcode/openfasttrace/blob/main/doc/user_guide.md#xml-tracing-report the prompt states:
`java -jar openfasttrace.jar trace -o aspac -f requirements.xml requirements`. Where `aspac` should be `aspec` with **e**
The error message states (leaving that here for someone stumbling up on this to find it):
`Exception in thread "main" org.itsallcode.openfasttrace.api.exporter.ExporterException: Found no matching reporter for output format 'aspac'`

Also I think the design/layout of tags should be restricted (as with the id names). Or at least I couldn't find any.  
*The following contains some theoretical (but possible) nastiness (sorry)*
- If there is a tag with a leading dash e.g. `-abc` This will lead to a problem: `--wanted-tags -abc`: `oft: No value for argument 'wantedtags'`.
-  If the dash is somewhere in the tag, the error is not shown but the tag is still not handled. 
- If a tag starts with `~` the first error is not happening but the tag is still not handled at all.
- And if I have a tag that is just a single underscore `_` that is handled but if I want to filter for just that tag with `--wanted-tags _` that will show me all tags (as desired by `--wanted-tags _`)
- There are probably more bad characters that should not be allowed as part of a tag (`>`, `?` ...)

If I should open Issues for the findings separately just give me a note and I will fix it. 

# Environment
- OFT: 4.0.1
- OS: Windows 10
- Java Version: 22

**Comment by kaklakariada** [comment]
@RobertZickler Thank you for taking the time and reporting all these issues!
I fixed most of them in #422. The last point about special characters in tags will be addressed in #423.
