### ISSUE TITLE
Support for reading Tags from Gherkin feature files

### ISSUE THREAD

**Issue by sophokles73** [itsallcode/openfasttrace#425]
The standard Tag importer supports reading tags from comments in a wide array of source code files.
Sadly, it is currently not possible to read Tags from `.feature` files as used with the [Gherkin language](https://cucumber.io/docs/gherkin/).

Gherkin also uses the `#` character to mark a line as a comment line. It should therefore be very easy to add support for _feature_ files because all that would need to be done is add `feature` to the standard Tag importer's list of supported file extensions.

**Comment by sophokles73** [comment]
I could provide a PR if you're interested ...

**Comment by kaklakariada** [comment]
Yes, that sounds good. Should only require adding the file suffix and a test.

**Comment by sophokles73** [comment]
Ok, I'll create a PR :-)
