### ISSUE TITLE
HTML Report

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/openfasttrace#89]
As a developer
I want a tracing report that is easy to ready
so that I can identify and fix gaps and errors in the tracing easily.

As a quality engineer
I want a report that I can view in a browser
so that I don't have to install any special tools on my machine when auditing a project.

As a customer
I want a report that I can understand and archive
so that I get a solid view of whether the team working for me does a good job.

# Acceptance Criteria
* OFT can produce an HTML report from a trace
* The HTML report contains everything relevant for quality assurance

**Comment by redcatbear** [comment]
Looking a template mechanisms:

Options

Engine | Last Commit | Repo | License | Runtime Dependencies | Notes
---------|------------------|--------|------------|-------------------------------|--------
Thymeleaf | 2017 | https://github.com/thymeleaf/thymeleaf | Apache 2.0 | javax.servlet, com.fasterxml.jackson.core, com.fasterxml.jackson.datatype |
Velocity | 2017 | http://svn.apache.org/viewvc/velocity/ | Apache 2.0 | slf4j, commons.lang |
MiniTemplator | 2012 | http://svn.source-code.biz/minitemplator-java/trunk/ | LGPL, EPL | none |
Jamon | 2012 | http://svn.code.sf.net/p/jamon/code/ | none | 2 stage, generates code from template

**Comment by redcatbear** [comment]
Jdynamite looks promissing so far.

**Comment by sascha15432** [comment]
+1 for Jdynamite but than we are going to violate the rule, that we don't pull in external dependencies at compile time. May we have to make a expection here for include a HTML template engine.
